# Generated by Django 6.0.1 on 2026-08-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='confidence',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='predicted_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
