# Generated by Django 6.0.1 on 2026-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_confidence_alter_resume_predicted_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
