# Generated by Django 6.0.1 on 2026-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_missing_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='recommended_jobs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
